#!/bin/sh
# Usage (intended): adb shell < drs_debloat
# [DRS_sprout | Nokia 3.4] Android 11 00WW_2_410_SP01 TA-1283

: <<'notice'
 * SPDX-License-Identifier: GPL-3.0
 *
 * Copyright (C) 2021 Dimitar Yurukov <mscalindt@protonmail.com>
 *
notice

pkg_rm() {
    pm uninstall --user 0 "$1"
}

pkg_clr() {
    pm clear --user 0 "$1"
}

main() {
    set -x

    # Unknown / Reverse engineer later to inspect requirability & bloatness
    ( return 1
        android.autoinstalls.config.hmdglobal.doctorstrange
        android.overlay.common
        android.overlay.target
        android.qvaoverlay.common
        com.android.apex.cts.shim
        com.android.apppredictionservice
        com.android.art
        com.android.backupconfirm
        com.android.bips
        com.android.bluetooth
        com.android.bluetoothmidiservice
        com.android.bookmarkprovider
        com.android.calllogbackup
        com.android.carrierconfig
        com.android.carrierconfig.overlay.common
        com.android.carrierdefaultapp
        com.android.cellbroadcastreceiver
        com.android.cellbroadcastreceiver.overlay.common
        com.android.certinstaller
        com.android.companiondevicemanager
        com.android.cts.ctsshim
        com.android.cts.priv.ctsshim
        com.android.dreams.basic
        com.android.dynsystem
        com.android.egg
        com.android.emergency
        com.android.externalstorage
        com.android.hotspot2.osulogin
        com.android.htmlviewer
        com.android.i18n
        com.android.inputdevices
        com.android.internal.display.cutout.emulation.corner
        com.android.internal.display.cutout.emulation.double
        com.android.internal.display.cutout.emulation.hole
        com.android.internal.display.cutout.emulation.tall
        com.android.internal.display.cutout.emulation.waterfall
        com.android.internal.systemui.navbar.gestural
        com.android.internal.systemui.navbar.gestural_extra_wide_back
        com.android.internal.systemui.navbar.gestural_narrow_back
        com.android.internal.systemui.navbar.gestural_wide_back
        com.android.internal.systemui.navbar.threebutton
        com.android.keychain
        com.android.launcher3
        com.android.localtransport
        com.android.location.fused
        com.android.managedprovisioning
        com.android.mms.service
        com.android.mtp
        com.android.musicfx
        com.android.nfc
        com.android.ons
        com.android.pacprocessor
        com.android.printspooler
        com.android.providers.blockednumber
        com.android.providers.calendar
        com.android.providers.contacts
        com.android.providers.downloads
        com.android.providers.downloads.ui
        com.android.providers.media
        com.android.providers.partnerbookmarks
        com.android.providers.settings
        com.android.providers.telephony
        com.android.providers.userdictionary
        com.android.proxyhandler
        com.android.runtime
        com.android.se
        com.android.server.telecom
        com.android.server.telecom.overlay.common
        com.android.sharedstoragebackup
        com.android.shell
        com.android.simappdialog
        com.android.smspush
        com.android.soundpicker
        com.android.statementservice
        com.android.storagemanager
        com.android.systemui
        com.android.systemui.overlay.common
        com.android.systemui.plugin.globalactions.wallet
        com.android.theme.color.amethyst
        com.android.theme.color.aquamarine
        com.android.theme.color.black
        com.android.theme.color.carbon
        com.android.theme.color.cinnamon
        com.android.theme.color.green
        com.android.theme.color.ocean
        com.android.theme.color.orchid
        com.android.theme.color.palette
        com.android.theme.color.purple
        com.android.theme.color.sand
        com.android.theme.color.space
        com.android.theme.color.tangerine
        com.android.theme.font.notoserifsource
        com.android.theme.icon.pebble
        com.android.theme.icon.roundedrect
        com.android.theme.icon.squircle
        com.android.theme.icon.taperedrect
        com.android.theme.icon.teardrop
        com.android.theme.icon.vessel
        com.android.theme.icon_pack.circular.android
        com.android.theme.icon_pack.circular.launcher
        com.android.theme.icon_pack.circular.settings
        com.android.theme.icon_pack.circular.systemui
        com.android.theme.icon_pack.circular.themepicker
        com.android.theme.icon_pack.filled.android
        com.android.theme.icon_pack.filled.launcher
        com.android.theme.icon_pack.filled.settings
        com.android.theme.icon_pack.filled.systemui
        com.android.theme.icon_pack.filled.themepicker
        com.android.theme.icon_pack.kai.android
        com.android.theme.icon_pack.kai.launcher
        com.android.theme.icon_pack.kai.settings
        com.android.theme.icon_pack.kai.systemui
        com.android.theme.icon_pack.kai.themepicker
        com.android.theme.icon_pack.rounded.android
        com.android.theme.icon_pack.rounded.launcher
        com.android.theme.icon_pack.rounded.settings
        com.android.theme.icon_pack.rounded.systemui
        com.android.theme.icon_pack.rounded.themepicker
        com.android.theme.icon_pack.sam.android
        com.android.theme.icon_pack.sam.launcher
        com.android.theme.icon_pack.sam.settings
        com.android.theme.icon_pack.sam.systemui
        com.android.theme.icon_pack.sam.themepicker
        com.android.theme.icon_pack.victor.android
        com.android.theme.icon_pack.victor.launcher
        com.android.theme.icon_pack.victor.settings
        com.android.theme.icon_pack.victor.systemui
        com.android.theme.icon_pack.victor.themepicker
        com.android.traceur
        com.android.vndk.v30
        com.android.vpndialogs
        com.android.wallpaper.livepicker
        com.android.wallpaperbackup
        com.android.wallpapercropper
        com.android.wifi
        com.android.wifi.resources
        com.android.wifi.resources.overlay.common
        com.android.wifi.resources.overlay.target
        com.google.android.adbd
        com.google.android.apps.restore
        com.google.android.apps.setupwizard.searchselector
        com.google.android.apps.work.oobconfig
        com.google.android.captiveportallogin
        com.google.android.cellbroadcast
        com.google.android.cellbroadcastreceiver
        com.google.android.cellbroadcastservice
        com.google.android.configupdater
        com.google.android.conscrypt
        com.google.android.dialer
        com.google.android.documentsui
        com.google.android.ext.shared
        com.google.android.extservices
        com.google.android.feedback
        com.google.android.gms.location.history
        com.google.android.googlequicksearchbox.overlay
        com.google.android.ipsec
        com.google.android.media
        com.google.android.media.swcodec
        com.google.android.mediaprovider
        com.google.android.modulemetadata
        com.google.android.networkstack
        com.google.android.networkstack.permissionconfig
        com.google.android.networkstack.tethering
        com.google.android.neuralnetworks
        com.google.android.onetimeinitializer
        com.google.android.os.statsd
        com.google.android.overlay.gmsconfig.common
        com.google.android.overlay.gmsconfig.comms
        com.google.android.overlay.gmsconfig.gsa
        com.google.android.overlay.gmsconfig.photos
        com.google.android.overlay.gmsconfig.searchlauncherqs
        com.google.android.overlay.modules.documentsui
        com.google.android.overlay.modules.ext.services
        com.google.android.overlay.modules.modulemetadata.forframework
        com.google.android.overlay.modules.permissioncontroller
        com.google.android.overlay.modules.permissioncontroller.forframework
        com.google.android.packageinstaller
        com.google.android.permission
        com.google.android.permissioncontroller
        com.google.android.printservice.recommendation
        com.google.android.providers.media.module
        com.google.android.resolv
        com.google.android.sdkext
        com.google.android.setupwizard
        com.google.android.syncadapters.contacts
        com.google.android.tag
        com.google.android.tethering
        com.google.android.tzdata2
        com.google.android.webview
        com.hmdglobal.app.activation
        com.hmdglobal.app.activation.overlay
        com.hmdglobal.app.customizationclient
        com.hmdglobal.app.legalinformation
        com.hmdglobal.app.omacp
        com.hmdglobal.app.setupwizardext
        com.qti.confuridialer
        com.qti.dpmserviceapp
        com.qti.ltebc
        com.qti.qualcomm.datastatusnotification
        com.qti.qualcomm.deviceinfo
        com.qti.service.colorservice
        com.qti.snapdragon.qdcm_ff
        com.qualcomm.embms
        com.qualcomm.location
        com.qualcomm.location.XT
        com.qualcomm.qcrilmsgtunnel
        com.qualcomm.qti.callfeaturessetting
        com.qualcomm.qti.cne
        com.qualcomm.qti.confdialer
        com.qualcomm.qti.ims
        com.qualcomm.qti.lpa
        com.qualcomm.qti.networksetting
        com.qualcomm.qti.poweroffalarm
        com.qualcomm.qti.qms.service.connectionsecurity
        com.qualcomm.qti.qms.service.trustzoneaccess
        com.qualcomm.qti.remoteSimlockAuth
        com.qualcomm.qti.services.secureui
        com.qualcomm.qti.services.systemhelper
        com.qualcomm.qti.simcontacts
        com.qualcomm.qti.simsettings
        com.qualcomm.qti.telephonyservice
        com.qualcomm.qti.uceShimService
        com.qualcomm.qti.uim
        com.qualcomm.qti.uimGbaApp
        com.qualcomm.qti.workloadclassifier
        com.qualcomm.qtil.aptxals
        com.qualcomm.qtil.aptxalsOverlay
        com.qualcomm.timeservice
        com.qualcomm.uimremoteclient
        com.qualcomm.uimremoteserver
        org.codeaurora.ims
        vendor.qti.hardware.cacert.server
    )

    # Removal not possible (bootloop)
    ( return 1
        pkg_rm com.google.android.ext.services
    )

    # Critical Android APIs (bad debloat)
    ( return 1
        # AR
        {
            pkg_rm com.google.ar.core
        }

        # Adaptive Battery
        {
            pkg_rm com.google.android.apps.turbo
        }

        # RCS / VoLTE
        {
            pkg_rm com.google.android.ims
        }

        # Smart Forwarding
        {
            pkg_rm com.qti.xdivert
        }

        # Telemetry Train
        {
            pkg_rm com.google.mainline.telemetry
        }

        # Wi-Fi Calling
        {
            pkg_rm com.google.android.wfcactivation
            pkg_rm vendor.qti.iwlan
        }

        # Wi-Fi Direct
        {
            pkg_rm com.qualcomm.atfwd
            pkg_rm com.qualcomm.wfd.service
        }
    )

    # Critical Google APIs (bad debloat)
    ( return 1
        pkg_rm com.google.android.gms
        pkg_rm com.google.android.gmsintegration
        pkg_rm com.google.android.gsf
        pkg_rm com.google.android.partnersetup
        pkg_rm com.google.android.tts
    )

    # Critical HMD APIs (bad debloat)
    ( return 1
        pkg_rm com.wos.face.service
    )

    # Critical Google apps (bad debloat)
    ( return 1
        pkg_rm com.android.chrome # Google Chrome
        pkg_rm com.android.vending # Play Store
    )

    # Safe Android APIs (safe debloat)
    (
        # Android Accessibility Suite
        {
            pkg_rm com.google.android.marvin.talkback
        }

        # Android Auto
        {
            pkg_rm com.google.android.projection.gearhead
        }

        # Digital Wellbeing | App stats
        {
            pkg_rm com.google.android.apps.wellbeing
        }

        # Widget for Android tips
        {
            pkg_rm com.android.protips
        }
    )

    # Safe Google APIs (safe debloat)
    (
        com.google.android.googlequicksearchbox.overlay
    )

    # Safe HMD APIs (safe debloat)
    (
        pkg_rm com.android.partnerbrowsercustomizations.hmdglobal
        pkg_rm com.hmdglobal.app.bokeheditor
        pkg_rm com.hmdglobal.app.myphonehelper
    )

    # Safe Android apps (safe debloat)
    (
        pkg_rm com.android.stk # SIM Toolkit
    )

    # Safe Google apps (safe debloat)
    (
        #pkg_rm com.google.android.calculator # Calculator
        #pkg_rm com.google.android.apps.nbu.files # Files
        #pkg_rm com.google.android.inputmethod.latin # Gboard
        #pkg_rm com.google.android.gm # Gmail
        pkg_rm com.google.android.googlequicksearchbox # Google
        pkg_rm com.google.android.apps.googleassistant # Google Assistant
        #pkg_rm com.google.android.calendar # Google Calendar
        pkg_rm com.google.android.apps.docs # Google Drive
        pkg_rm com.google.android.apps.tachyon # Google Duo
        pkg_rm com.google.android.keep # Google Keep
        pkg_rm com.google.ar.lens # Google Lens
        pkg_rm com.google.android.apps.maps # Google Maps
        pkg_rm com.google.android.apps.magazines # Google News
        pkg_rm com.google.android.apps.subscriptions.red # Google One
        pkg_rm com.google.android.apps.walletnfcrel # Google Pay
        pkg_rm com.google.android.apps.photos # Google Photos
        pkg_rm com.google.android.apps.podcasts # Google Podcasts
        #pkg_rm com.google.android.apps.wallpaper # Google Wallpapers
        pkg_rm com.google.android.youtube # YouTube
        pkg_rm com.google.android.apps.youtube.music # YouTube Music
    )

    # Safe HMD apps (safe debloat)
    (
        pkg_rm com.hmdglobal.app.camera # Camera
        pkg_rm com.hmdglobal.app.fmradio # FM Radio
        pkg_rm com.hmdglobal.support # My phone | My device
    )

    # Literal sh1t (asap remove)
    (
        pkg_rm com.amazon.appmanager
        pkg_rm com.netflix.mediaclient
        pkg_rm com.qualcomm.qti.qms.service.telemetry
    )

    # Apps&APIs to be reset to clean state
    ( return 1
        pkg_clr com.google.android.ext.services # Android Services Library
        pkg_clr com.google.android.deskclock # Clock
        pkg_clr com.google.android.contact # Contacts
        pkg_clr com.wos.face.service # Face detection
        pkg_clr com.google.android.gms # Google Play Services
        pkg_clr com.google.android.gsf # Google Services Framework
        pkg_clr com.google.android.apps.messaging # Messages
        pkg_clr com.android.phone # Phone
        pkg_clr com.android.vending # Play Store
        pkg_clr com.android.settings # Settings
        pkg_clr com.google.android.tts # Speech Services | Google Text-to-Speech
    )
}

main "$@"
