#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2021-2022 Dimitar Yurukov <mscalindt@protonmail.com>
# Usage (intended): adb shell < drs_debloat
# [DRS_sprout | Nokia 3.4] Android 12 00WW_3_330 TA-1283

pkg_rm() (
    _errh() { return "$1"; }
    trap '_errh $?' INT TERM EXIT; set -e

    DIR='/storage/emulated/0/Android'

    pm clear --user 0 "$1"
    pm uninstall --user 0 "$1"
    rm -rf "$DIR/data/$1"
    rm -rf "$DIR/media/$1"
    rm -rf "$DIR/obb/$1"
)

pkg_clr() (
    _errh() { return "$1"; }
    trap '_errh $?' INT TERM EXIT; set -e

    DIR='/storage/emulated/0/Android'

    pm clear --user 0 "$1"

    rm -rf "$DIR/data/$1"/*
)

main() {
    set -x

    # Full stock app list
    ( return 1
        package:com.google.android.networkstack.tethering
        package:com.amazon.mShop.android.shopping
        package:com.google.android.apps.subscriptions.red
        package:com.android.cts.priv.ctsshim
        package:com.qualcomm.qti.qms.service.telemetry
        package:com.google.android.youtube
        package:com.android.internal.display.cutout.emulation.corner
        package:com.google.android.ext.services
        package:com.android.internal.display.cutout.emulation.double
        package:com.android.providers.telephony
        package:com.android.dynsystem
        package:com.google.android.googlequicksearchbox
        package:com.google.android.cellbroadcastservice
        package:com.android.providers.calendar
        package:com.google.android.apps.googleassistant
        package:com.android.providers.media
        package:com.qti.service.colorservice
        package:com.google.android.onetimeinitializer
        package:com.google.android.ext.shared
        package:com.android.internal.systemui.navbar.gestural_wide_back
        package:com.qualcomm.qti.simcontacts
        package:com.android.wallpapercropper
        package:com.google.android.googlequicksearchbox.overlay
        package:com.android.protips
        package:com.google.android.apps.podcasts
        package:com.android.externalstorage
        package:com.qualcomm.uimremoteclient
        package:com.android.htmlviewer
        package:com.qualcomm.qti.uceShimService
        package:com.android.companiondevicemanager
        package:com.hmdglobal.app.activation
        package:com.android.mms.service
        package:com.wos.face.service
        package:com.qualcomm.qti.qms.service.connectionsecurity
        package:com.android.providers.downloads
        package:com.qualcomm.qtil.aptxalsOverlay
        package:com.hmdglobal.entitlementcheck
        package:com.google.android.apps.messaging
        package:com.android.internal.systemui.onehanded.gestural
        package:vendor.qti.hardware.cacert.server
        package:android.autoinstalls.config.hmdglobal.doctorstrange
        package:com.qualcomm.qti.telephonyservice
        package:vendor.qti.iwlan
        package:com.google.android.configupdater
        package:com.google.android.providers.media.module
        package:com.google.android.overlay.modules.permissioncontroller
        package:com.qualcomm.uimremoteserver
        package:com.qti.confuridialer
        package:android.qvaoverlay.common
        package:com.android.providers.downloads.ui
        package:com.android.vending
        package:com.android.pacprocessor
        package:com.android.simappdialog
        package:android.overlay.common
        package:com.android.internal.display.cutout.emulation.hole
        package:com.android.internal.display.cutout.emulation.tall
        package:com.android.certinstaller
        package:com.android.carrierconfig
        package:com.google.android.marvin.talkback
        package:com.hmdglobal.app.customizationclient
        package:com.android.internal.systemui.navbar.threebutton
        package:com.hmdglobal.app.activation.overlay
        package:com.qti.qualcomm.datastatusnotification
        package:com.hmdglobal.app.fmradio
        package:android
        package:com.qualcomm.qti.callfeaturessetting
        package:com.qualcomm.wfd.service
        package:com.qualcomm.qtil.aptxacu
        package:com.qualcomm.qtil.aptxals
        package:com.qti.qualcomm.deviceinfo
        package:com.android.egg
        package:com.android.mtp
        package:com.android.nfc
        package:com.android.ons
        package:com.android.stk
        package:com.android.launcher3
        package:com.android.backupconfirm
        package:com.google.android.deskclock
        package:org.codeaurora.ims
        package:com.google.android.gm
        package:com.hmdglobal.app.myphonehelper
        package:android.overlay.target
        package:com.google.android.apps.tachyon
        package:com.google.android.overlay.gmsconfig.common
        package:com.android.settings.intelligence
        package:com.android.internal.systemui.navbar.gestural_extra_wide_back
        package:com.google.android.permissioncontroller
        package:com.google.android.setupwizard
        package:com.qualcomm.qcrilmsgtunnel
        package:com.android.providers.settings
        package:com.android.sharedstoragebackup
        package:com.android.printspooler
        package:com.qualcomm.qti.services.systemhelper
        package:com.android.wifi.resources.overlay.common
        package:com.android.dreams.basic
        package:com.google.android.overlay.modules.ext.services
        package:com.android.se
        package:com.android.inputdevices
        package:com.google.android.apps.wellbeing
        package:com.google.android.overlay.gmsconfig.photos
        package:com.google.android.dialer
        package:com.android.bips
        package:com.qti.dpmserviceapp
        package:com.google.android.apps.nbu.files
        package:com.google.android.captiveportallogin
        package:com.google.android.overlay.gmsconfig.comms
        package:com.google.android.overlay.gmsconfig.geotz
        package:com.qti.xdivert
        package:com.android.musicfx
        package:com.android.settings.overlay.common
        package:com.hmdglobal.app.setupwizardext
        package:com.google.android.apps.docs
        package:com.google.android.apps.maps
        package:com.google.android.modulemetadata
        package:com.google.android.overlay.gmsconfig.searchlauncherqs
        package:com.google.android.cellbroadcast.overlay
        package:com.android.cellbroadcastreceiver
        package:com.google.android.webview
        package:com.google.android.overlay.modules.documentsui
        package:com.amazon.appmanager
        package:com.google.android.networkstack
        package:com.google.android.contacts
        package:com.android.server.telecom
        package:com.google.android.syncadapters.contacts
        package:com.android.keychain
        package:com.qti.snapdragon.qdcm_ff
        package:com.android.wifi.resources.overlay.target
        package:com.google.android.calculator
        package:com.android.chrome
        package:com.google.android.packageinstaller
        package:com.google.android.apps.customization.pixel
        package:com.google.android.gms
        package:com.google.android.gsf
        package:com.google.android.ims
        package:com.google.android.tag
        package:com.google.android.tts
        package:com.android.wifi.resources
        package:com.google.android.gmsintegration
        package:com.android.phone.overlay.common
        package:com.android.carrierconfig.overlay.common
        package:com.google.android.apps.walletnfcrel
        package:com.android.calllogbackup
        package:com.google.android.partnersetup
        package:com.android.systemui.overlay.common
        package:com.android.cameraextensions
        package:com.android.server.telecom.overlay.common
        package:com.android.localtransport
        package:com.google.android.videos
        package:com.google.android.overlay.gmsconfig.gsa
        package:com.android.carrierdefaultapp
        package:com.hmdglobal.app.camera
        package:com.qualcomm.qti.remoteSimlockAuth
        package:com.android.theme.font.notoserifsource
        package:com.android.proxyhandler
        package:com.android.internal.display.cutout.emulation.waterfall
        package:com.qualcomm.qti.workloadclassifier
        package:com.netflix.mediaclient
        package:com.google.android.connectivity.resources
        package:com.google.android.overlay.modules.permissioncontroller.forframework
        package:com.google.android.feedback
        package:com.google.android.printservice.recommendation
        package:com.google.android.apps.photos
        package:com.google.android.calendar
        package:com.android.managedprovisioning
        package:com.android.soundpicker
        package:com.android.partnerbrowsercustomizations.hmdglobal
        package:com.google.android.documentsui
        package:com.google.mainline.telemetry
        package:com.android.providers.partnerbookmarks
        package:com.android.smspush
        package:com.android.wallpaper.livepicker
        package:com.android.imsserviceentitlement
        package:com.google.android.networkstack.permissionconfig
        package:com.android.storagemanager
        package:com.android.bookmarkprovider
        package:com.android.settings
        package:com.qualcomm.qti.cne
        package:com.qualcomm.qti.ims
        package:com.qualcomm.qti.lpa
        package:com.qualcomm.qti.uim
        package:com.google.android.wfcactivation
        package:com.hmdglobal.support
        package:com.google.android.projection.gearhead
        package:com.qualcomm.location
        package:com.google.android.apps.turbo
        package:com.google.android.apps.chromecast.app
        package:com.android.cts.ctsshim
        package:com.google.android.overlay.modules.modulemetadata.forframework
        package:com.qualcomm.qti.uimGbaApp
        package:com.qualcomm.qti.services.secureui
        package:com.android.vpndialogs
        package:com.qualcomm.location.XT
        package:com.google.android.apps.wallpaper
        package:com.hmdglobal.app.devicelock
        package:com.android.music
        package:com.android.phone
        package:com.android.shell
        package:com.android.wallpaperbackup
        package:com.android.providers.blockednumber
        package:com.android.providers.userdictionary
        package:com.google.android.apps.setupwizard.searchselector
        package:com.android.emergency
        package:com.qualcomm.qti.seccamservice
        package:com.android.hotspot2.osulogin
        package:com.google.android.gms.location.history
        package:com.android.internal.systemui.navbar.gestural
        package:com.android.location.fused
        package:com.hmdglobal.app.omacp
        package:com.android.systemui
        package:com.google.android.apps.youtube.music
        package:com.android.bluetoothmidiservice
        package:com.qualcomm.qti.confdialer
        package:com.qualcomm.qti.poweroffalarm
        package:com.qti.ltebc
        package:com.qti.phone
        package:com.hmdglobal.app.bokeheditor
        package:com.android.traceur
        package:com.google.android.cellbroadcastreceiver
        package:com.android.apppredictionservice
        package:com.qualcomm.qti.qms.service.trustzoneaccess
        package:com.hmdglobal.app.legalinformation
        package:com.qualcomm.qtil.aptxui
        package:com.google.android.apps.magazines
        package:com.android.bluetooth
        package:com.qualcomm.timeservice
        package:com.qualcomm.atfwd
        package:com.qualcomm.embms
        package:com.android.providers.contacts
        package:vendor.qti.imsrcs
        package:com.android.internal.systemui.navbar.gestural_narrow_back
        package:com.android.cellbroadcastreceiver.overlay.common
        package:com.google.android.inputmethod.latin
        package:com.google.android.apps.restore
    )

    # Removal not possible (bootloop)
    ( return 1
        pkg_rm com.google.android.ext.services
    )

    # Critical Android APIs (bad debloat)
    ( return 1
        # AR
        #{
        #    pkg_rm com.google.ar.core
        #}

        # Adaptive Battery
        {
            pkg_rm com.google.android.apps.turbo
        }

        # RCS / VoLTE
        {
            pkg_rm com.google.android.ims
        }

        # Smart Forwarding
        {
            pkg_rm com.qti.xdivert
        }

        # Telemetry Train
        {
            pkg_rm com.google.mainline.telemetry
        }

        # Wi-Fi Calling
        {
            pkg_rm com.google.android.wfcactivation
            pkg_rm vendor.qti.iwlan
        }

        # Wi-Fi Direct
        {
            pkg_rm com.qualcomm.atfwd
            pkg_rm com.qualcomm.wfd.service
        }
    )

    # Critical Google APIs (bad debloat)
    ( return 1
        pkg_rm com.google.android.gms
        pkg_rm com.google.android.gmsintegration
        pkg_rm com.google.android.gsf
        pkg_rm com.google.android.partnersetup
        pkg_rm com.google.android.tts
    )

    # Critical HMD APIs (bad debloat)
    ( return 1
        pkg_rm com.wos.face.service
    )

    # Critical Google apps (bad debloat)
    ( return 1
        pkg_rm com.android.chrome # Google Chrome
        pkg_rm com.android.vending # Play Store
    )

    # Safe Android APIs (safe debloat)
    (
        # Android Accessibility Suite
        {
            pkg_rm com.google.android.marvin.talkback
        }

        # Android Auto
        {
            pkg_rm com.google.android.projection.gearhead
        }

        # Digital Wellbeing | App stats
        {
            pkg_rm com.google.android.apps.wellbeing
        }

        # Widget for Android tips
        {
            pkg_rm com.android.protips
        }
    )

    # Safe Google APIs (safe debloat)
    (
        com.google.android.googlequicksearchbox.overlay
    )

    # Safe HMD APIs (safe debloat)
    (
        pkg_rm com.android.partnerbrowsercustomizations.hmdglobal
        pkg_rm com.hmdglobal.app.bokeheditor
        pkg_rm com.hmdglobal.app.myphonehelper
    )

    # Safe Android apps (safe debloat)
    (
        pkg_rm com.android.stk # SIM Toolkit
    )

    # Safe Google stock apps (bad debloat)
    ( return 1
        pkg_rm com.google.android.calculator # Calculator
        pkg_rm com.google.android.inputmethod.latin # Gboard
        pkg_rm com.google.android.calendar # Google Calendar
    )

    # Safe Google apps (safe debloat)
    (
        pkg_rm com.google.android.apps.nbu.files # Files
        #pkg_rm com.google.android.gm # Gmail
        #pkg_rm com.google.android.googlequicksearchbox # Google
        #pkg_rm com.google.android.apps.googleassistant # Google Assistant
        pkg_rm com.google.android.apps.docs # Google Drive
        pkg_rm com.google.android.apps.tachyon # Google Duo
        pkg_rm com.google.android.apps.chromecast.app # Google Home
        pkg_rm com.google.android.keep # Google Keep
        #pkg_rm com.google.ar.lens # Google Lens
        #pkg_rm com.google.android.apps.maps # Google Maps
        pkg_rm com.google.android.apps.magazines # Google News
        pkg_rm com.google.android.apps.subscriptions.red # Google One
        pkg_rm com.google.android.apps.walletnfcrel # Google Pay
        pkg_rm com.google.android.apps.photos # Google Photos
        pkg_rm com.google.android.apps.podcasts # Google Podcasts
        pkg_rm com.google.android.videos # Google TV
        #pkg_rm com.google.android.apps.wallpaper # Google Wallpapers
        pkg_rm com.google.android.youtube # YouTube
        pkg_rm com.google.android.apps.youtube.music # YouTube Music
    )

    # Safe HMD apps (safe debloat)
    (
        pkg_rm com.hmdglobal.app.camera # Camera
        pkg_rm com.hmdglobal.app.fmradio # FM Radio
        pkg_rm com.hmdglobal.support # My phone | My device (my soul my heart)
    )

    # Literal sh1t (*ASAP* remove)
    (
        pkg_rm com.amazon.appmanager
        pkg_rm com.amazon.mShop.android.shopping
        pkg_rm com.netflix.mediaclient
        pkg_rm com.qualcomm.qti.qms.service.telemetry
    )

    # Apps&APIs to be reset to clean state (not needed usually)
    ( return 1
        pkg_clr com.google.android.ext.services # Android Services Library
        pkg_clr com.google.android.deskclock # Clock
        pkg_clr com.google.android.contacts # Contacts
        pkg_clr com.wos.face.service # Face detection
        pkg_clr com.google.android.gms # Google Play Services
        pkg_clr com.google.android.gsf # Google Services Framework
        pkg_clr com.google.android.apps.messaging # Messages
        pkg_clr com.android.phone # Phone
        pkg_clr com.android.vending # Play Store
        pkg_clr com.android.settings # Settings
        pkg_clr com.google.android.tts # Speech Services | Google Text-to-Speech
    )

    return 0
}

main "$@"
