#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2021-2022 Dimitar Yurukov <mscalindt@protonmail.com>

main() {
    gsdl2="$HOME/.steam/steam/steamapps/common/Half-Life/libSDL2-2.0.so.0"
    nloc="$HOME/.steam/steam/steamapps/common/Half-Life/libSDL2-2.0.so.0.old"

    if [ -f "$gsdl2" ]; then
        mv -f "$gsdl2" "$nloc"
    fi

    unset gsdl2
    unset nloc

    GAMEEXE='hl_linux -steam -game bshift'
    export GAMEEXE
    "$1" -w 1920 -h 1080

    return $?
}

main "$@"
