#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

ffmpeg_get_to() (
    err() {
        trap - INT TERM EXIT

        if [ "$1" != 0 ]; then
            printf "%s" \
'
$1 -> input
$2 -> time HH:MM:SS[.SSS]
$3 -> fname
$4 *a* -> `-avoid_negative_ts disabled` (might break players) OR \
$4 *b* -> `-avoid_negative_ts make_zero` (might still choke players)
$4 *d* -> `-loglevel debug`
$4 *m* -> dont keep mtime
$4 *p* -> (NO-OP) precise (exact frame) cut; pay $666k for FLAWLESS implementation :)
$4 *t* -> no cleanup/move (only on success)
$4 *u* -> work in current dir
$4 *v* -> verbose/developer output
'

            rm -rf "$ODIR"
        fi

        case "$OPTS" in
            *t*) : ;;
            *) rm -rf "$ODIR" ;;
        esac

        exit "$1"
    }

    # turn pts_time (ms scaled) timestamp into HH:MM:SS.SSS timestamp
    # e.g. 3617.666 -> 01:00:17.666
    # $1 = val
    # $2 = var name
    conv_pts_time_ms() {
        # assert input
        case "$1" in
            *.[0-9][0-9][0-9]) ;;
            *) echo 'input error'; exit 255 ;;
        esac
        case "$2" in
            [0-9]*)
                return 1
            ;;
            *[!0-9A-Za-z_]*)
                return 1
            ;;
        esac
        [ "$2" ] || { echo 'input error'; exit 255; }

        _ts="${1%.*}"
        _ts="${_ts#"${_ts%%[!0]*}"}" && [ "$_ts" ] || _ts=0

        _hh=$((_ts / 3600)); [ "${#_hh}" -ne 1 ] || _hh="0$_hh"
        _mm=$(((_ts % 3600) / 60)); [ "${#_mm}" -ne 1 ] || _mm="0$_mm"
        _ss=$((_ts % 60)); [ "${#_ss}" -ne 1 ] || _ss="0$_ss"
        _ms="${1#*.}"

        eval "$2=\"\$_hh:\$_mm:\$_ss.\$_ms\""
    }

    # print debug info
    # $1 = debug tag
    # $2 = string
    d() {
        printf "%b[%s] %b%s: %b%s%b\n" \
            '\033[1;35m' \
            'D' \
            '\033[1;37m' \
            "${1:-DEBUG}" \
            '\033[1;30m' \
            "$2" \
            '\033[0m'
    }

    # turn a timestamp into a scaled integer (with ms precision; no dot)
    # e.g. 01:00:17.666 -> 3617666 (scale factor = 1000)
    # $1 = val
    # $2 = var name
    scale_ms() {
        case "$1" in
            *'.'*) _ts="${1%.*}" ;;
            *) _ts="$1" ;;
        esac
        case "$2" in
            [0-9]*)
                return 1
            ;;
            *[!0-9A-Za-z_]*)
                return 1
            ;;
        esac
        [ "$2" ] || { echo 'input error'; exit 255; }

        _hh="${_ts%??????}"
        _hh="${_hh#0}"
        _mm="${_ts#???}"
        _mm="${_mm%???}"
        _mm="${_mm#0}"
        _ss="${_ts#??????}"
        _ss="${_ss#0}"
        case "$1" in
            *'.'*) _ms="${1#*.}" ;;
            *) _ms=000 ;;
        esac

        _time="$_ss"
        _time=$((_time + (_mm * 60)))
        _time=$((_time + (_hh * 3600)))
        eval "$2=\"\$_time\$_ms\""
    }

    # $1 = diff var name
    # $2 = prev diff var name
    # $3 = our ts var name
    # $4 = pts_time ts var name
    # $5 = prev pts_time ts var name
    snap() {
        for _name in "$1" "$2" "$3" "$4" "$5"; do
            case "$_name" in
                [0-9]*)
                    return 1
                ;;
                *[!0-9A-Za-z_]*)
                    return 1
                ;;
            esac
            [ "$_name" ] || { echo 'input error'; exit 255; }
        done

        eval "_diff=\"\$$1\""
        eval "_pdiff=\"\$$2\""
        eval "_ts=\"\$$3\""
        eval "_TS=\"\$$4\""
        eval "_pTS=\"\$$5\""

        # assert pts_time timestamp
        case "$_TS" in
            *.[0-9][0-9][0-9][0-9][0-9][0-9]) ;;
            *) echo 'input error'; exit 255 ;;
        esac

        # strip us (microseconds) from pts_time
        _TS="${_TS%???}"

        # scale by 1000
        _TS="${_TS%".${_TS#*.}"}${_TS#"${_TS%.*}."}"

        # ensure operands remain interpreted as decimal in shell arithmetic
        _ts="${_ts#"${_ts%%[!0]*}"}" && [ "$_ts" ] || _ts=0
        _TS="${_TS#"${_TS%%[!0]*}"}" && [ "$_TS" ] || _TS=0

        _diff=$((_ts - _TS))
        _diff="${_diff#-}"
        if [ "$_diff" -gt "${_pdiff:-$_diff}" ] || \
           [ "$_diff" = "$_pdiff" ]; then
            eval "$1=\"\$$1\""
            eval "$2=\"\$$2\""
            eval "$3=\"\$$3\""
            eval "$4=\"\$$5\""
            eval "$5=\"\$$5\""
            return 0
        fi
        eval "$1=\"\$_diff\""
        eval "$2=\"\$_diff\""
        eval "$3=\"\$$3\""
        eval "$4=\"\$$4\""
        eval "$5=\"\$$4\""
        [ "$_diff" = 0 ]
    }

    set -e
    LC_ALL=C; export LC_ALL
    ODIR=
    trap "err \$?" INT TERM EXIT

    IN="$1"
    TIME="$2"
    FNAME="$3"
    OPTS="$4"
    DIR=$(cd -Pe "$PWD" && printf "%s" "$PWD.")
    DIR="${DIR%.}"

    case "$OPTS" in
        *u*) _ODIR="$DIR"/.ffmpeg_get_to ;;
        *) _ODIR="${TMPDIR:-/tmp}"/.ffmpeg_get_to ;;
    esac

    if [ -e "$_ODIR" ]; then
        printf "%s" "Sweetie, '$_ODIR' already exists... Shall I delete it? [y/N] "

        read -r _action; [ "$_action" ] || _action=N
        case "$_action" in
            [Yy]*) ODIR="$_ODIR" ;;
            *) printf "%s\n" 'Sweetheart... wise choice! Deal with it.'; exit 1 ;;
        esac
    else
        ODIR="$_ODIR"
    fi

    [ "$IN" ] || { printf "%s\n" 'No input file specified.'; exit 2; }
    [ -e "$IN" ] || { printf "%s\n" 'Bad input. (ENOENT)'; exit 2; }
    [ ! -d "$IN" ] || { printf "%s\n" 'Bad input. (EISDIR)'; exit 2; }

    case "$IN" in
        */*)
            IN="$(realpath -- "$IN" && printf "%s" .)"
            IN="${IN%?.}"

            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            DIR="${IN%/*}"
        ;;
        *)
            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            IN="$DIR"/"$IN"
        ;;
    esac

    # (BEST EFFORT)
    # Match extensions to the equivalent ffmpeg format names.
    case "$FMT" in
        'm4a') FMT=mp4 ;;
    esac

    [ -e "$IN" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }

    [ "$TIME" ] || { printf "%s\n" 'No TO time specified.'; exit 2; }
    case "$TIME" in
        [0-9][0-9]:[0-9][0-9]:[0-9][0-9] | \
        [0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9])
            # assert there is at least one unit of time
            case "$TIME" in
                *[1-9]*) : ;;
                *) printf "%s\n" 'Invalid TO time.'; exit 2 ;;
            esac
        ;;
        *)
            printf "%s\n" 'Invalid TO time.'; exit 2
        ;;
    esac

    # guarantee we are in our custom empty dir
    # otherwise globbing cannot be trusted
    rm -rf "$ODIR"
    mkdir "$ODIR"
    cd "$ODIR"

    case "$OPTS" in
        *v*)
            d 'cksum' "$(cksum "$IN")"
            d 'stream=index,codec_name,codec_type,has_b_frames,time_base,start_pts,start_time,duration' "
$(
    ffprobe \
        -v 16 \
        -show_entries stream=index,codec_name,codec_type,has_b_frames,time_base,start_pts,start_time,duration \
        "$IN"
)"
        ;;
    esac

    # compute the snap to nearest keyframe/packet (video/audio) timestamp
    # to show and use it. on videos, only keyframes are considered,
    # even though a keyframe landing on a packet (audio) timestamp would be
    # beneficial to avoid worst-case imperceptible ~23ms AV desync.
    #
    # must convert the time to seconds with ms precision using scale_ms()
    # to match pts_time unit (us). thus, error tolerance is us (microseconds),
    # e.g. 6.666 == 6.666777, but 6.666 != 6.667 (this is considered a snap),
    # because ms is significant.
    #
    # requires at least ffmpeg 7.0 or newer, where the claim about pts_time
    # unit having us precision holds true.
    scale_ms "$TIME" time1
    type=$(
        ffprobe \
            -v 16 \
            -select_streams 0 \
            -show_entries stream=codec_type \
            -of compact=p=0:nk=1 \
            "$IN"
    )
    [ "$type" = video ] || [ "$type" = audio ] || \
    { printf "%s\n" 'Unsupported input. (could not determine type)'; exit 1; }
    echo 'Computing timestamps...'
    keyts=$(
        ffprobe \
            -v 16 \
            -select_streams "${type%"${type#?}"}" \
            -show_entries packet=pts_time,flags \
            -of compact=p=0:nk=1 \
            "$IN"
    )
    case "$OPTS" in
        *v*)
            d 'packet=pts_time,flags' "${keyts//
/ }"
        ;;
    esac
    # get keyframes only
    keyts=$(
        printf "%s\n" "$keyts" | while IFS= read -r LINE; do
            case "$LINE" in
                *'K'*) printf "%s\n" "${LINE%%|*}" ;;
            esac
        done
    )
    # using snap(), compare the timestamps to our scaled integer timestamp
    # using relative difference. for middle collision, choose lower
    # timestamp. snap() internally does not differentiate the snap
    # and just dynamically updates the specified variables, but for us:
    # diff 0 == no snap;
    # otherwise lowest diff == closest ts == snap.
    diff1=; pdiff1=
    pTS=  # $TS is empty on overshoot, so store it in $pTS
    while IFS= read -r TS; do
        case "$TS" in
            '-'*) continue ;;  # skip negative ts
            '0.000'*) continue ;;  # skip first/no-op ts
        esac
        if snap diff1 pdiff1 time1 TS pTS; then
            break
        fi
    done \
<<EOF
$keyts
EOF
    [ "$diff1" ] || { printf "%s\n" 'No key timestamps available.'; exit 1; }
    [ "$TS" ] || TS="$pTS"; TS1="$TS"
    if [ "$diff1" != 0 ]; then
        # just for your convenience sweetheart, $TS1 will be converted to
        # HH:MM:SS.SSS. no need to thank me!
        conv_pts_time_ms "${TS1%???}" _TS1
        printf "%b%s: To %s (%s) instead of %s%b\n" \
            '\033[1;33m' \
            'SNAP TO NEAREST KEY TIMESTAMP' \
            "$TS1" \
            "$_TS1" \
            "$TIME" \
            '\033[0m'
    fi
    TIME="$TS1"

    # global options shall follow first.
    set -- 'ffmpeg'
    set -- "$@" '-hide_banner'
    case "$OPTS" in
        *d*) set -- "$@" '-loglevel' 'debug' ;;
    esac

    # nearest keyframe cut; all lossless; no side effects.
    #
    # note that, we trust that the container is not malformed for this to
    # actually work as intended.
    #
    # after these options, only output options shall follow.
    set -- "$@" '-to' "$TIME"
    set -- "$@" '-i' "$IN"

    # adjusting the container PTS/DTS does not cause re-encoding whatsoever.
    case "$OPTS" in
        *a*)
            set -- "$@" '-avoid_negative_ts' 'disabled'  # 0
        ;;
        *b*)
            set -- "$@" '-avoid_negative_ts' 'make_zero'  # 2
        ;;
        *)
            set -- "$@" '-avoid_negative_ts' 'make_non_negative'  # 1
        ;;
    esac
    set -- "$@" '-c' 'copy'
    set -- "$@" '-map' '0'
    set -- "$@" '-f' "$FMT"
    set -- "$@" "${IN##*/}"

    case "$OPTS" in
        *v*) d 'cmdline' "$*" ;;
    esac
    "$@"

    # from now on guarantee $FILE is just the filename as we are in our dir
    # simplifies operations
    set -- *
    FILE="$1"
    if [ ! -e "$FILE" ]; then
        set -- .*; while [ "$1" ]; do case "$1" in
            '.' | '..') shift ;;
            *) FILE="$1" && break ;;
        esac; done
    fi
    [ -e "$FILE" ] || { printf "%s\n" 'File glob failed. (ENOENT)'; exit 1; }
    [ ! -d "$FILE" ] || { printf "%s\n" 'File glob failed. (EISDIR)'; exit 1; }

    case "$OPTS" in
        *v*)
            d 'stream=index,codec_name,codec_type,has_b_frames,time_base,start_pts,start_time,duration' "
$(
    ffprobe \
        -v 16 \
        -show_entries stream=index,codec_name,codec_type,has_b_frames,time_base,start_pts,start_time,duration \
        "$FILE"
)"
            d 'cksum' "$(cksum "$FILE")"
        ;;
    esac

    case "$OPTS" in
        *m*) : ;;
        *) touch -r "$IN" "$FILE" ;;
    esac

    # rename in our dir
    # if $IN has extension, append it to $FNAME
    if [ "$FNAME" ]; then
        case "$IN" in
            *.?? | *.??? | *.????) FNAME="$FNAME.${IN##*.}" ;;
        esac

        # guard same filename rename
        case "$FILE" in
            "$FNAME") : ;;
            *) mv "$FILE" "$FNAME" ;;
        esac

        FILE="$FNAME"
    fi

    # move result to dest
    case "$OPTS" in
        *t*)
            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$ODIR"/"$FILE" '\033[0m'
        ;;
        *)
            # guaranteed move, no need for guard
            # `-f` because typically output loc/name might match input loc
            mv -f "$FILE" "$DIR"/"$FILE"

            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$DIR"/"$FILE" '\033[0m'
        ;;
    esac
)

ffmpeg_get_to "$@"
