#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

ffmpeg_concat() (
    err() {
        trap - INT TERM EXIT

        if [ "$1" != 0 ]; then
            printf "%s" \
'
$1 -> input 1
$2 -> input 2
$3 -> fname
$4 *a* -> out PTS/DTS as-is (might choke players)
$4 *d* -> `-loglevel debug`
$4 *i* -> `-map_metadata 1` (global metadata from input 2 instead of 1)
$4 *m* -> dont keep mtime
$4 *n* -> keep mtime of input 2
$4 *t* -> no cleanup/move (only on success)
$4 *u* -> work in current dir
'

            rm -rf "$ODIR"
        fi

        case "$OPTS" in
            *t*) : ;;
            *) rm -rf "$ODIR" ;;
        esac

        exit "$1"
    }

    set -e
    trap "err \$?" INT TERM EXIT

    IN="$1"
    IN2="$2"
    FNAME="$3"
    OPTS="$4"
    DIR=$(cd -Pe "$PWD" && printf "%s" "$PWD.")
    DIR="${DIR%.}"

    case "$OPTS" in
        *u*) ODIR="$DIR"/.ffmpeg_concat ;;
        *) ODIR="${TMPDIR:-/tmp}"/.ffmpeg_concat ;;
    esac

    [ "$IN" ] || { printf "%s\n" 'No input file specified.'; exit 2; }
    [ -e "$IN" ] || { printf "%s\n" 'Bad input. (ENOENT)'; exit 2; }
    [ ! -d "$IN" ] || { printf "%s\n" 'Bad input. (EISDIR)'; exit 2; }

    case "$IN" in
        */*)
            IN="$(realpath -- "$IN" && printf "%s" .)"
            IN="${IN%?.}"

            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            DIR="${IN%/*}"
        ;;
        *)
            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            IN="$DIR"/"$IN"
        ;;
    esac

    [ -e "$IN" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }

    [ "$IN2" ] || { printf "%s\n" 'No second file specified.'; exit 2; }
    [ -e "$IN2" ] || { printf "%s\n" 'Bad second file. (ENOENT)'; exit 2; }
    [ ! -d "$IN2" ] || { printf "%s\n" 'Bad second file. (EISDIR)'; exit 2; }

    IN2="$(realpath -- "$IN2" && printf "%s" .)"
    IN2="${IN2%?.}"

    [ -e "$IN2" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }

    # guarantee we are in our custom empty dir
    # otherwise globbing cannot be trusted
    rm -rf "$ODIR"
    mkdir "$ODIR"
    cd "$ODIR"

    ShePoludeem=$(
        printf "file '%s'\n" "${IN//\'/\'\\\'\'}"
        printf "file '%s'\n" "${IN2//\'/\'\\\'\'}"
    )
    printf "%s" "$ShePoludeem" > ShePoludeem.txt

    set -- 'ffmpeg'
    set -- "$@" '-hide_banner'

    # fully regenerate PTS/DTS container timestamps by default for monotonic
    # timeline. a timeline that is not monotonic can choke players.
    #
    # in either case, PTS/DTS do not affect the produced video/audio (packet)
    # data; only the container's PTS/DTS get regenerated when not re-encoding
    # (and `+genpts` will *not* force re-encode).
    #
    # if source PTS/DTS are 100% correct, `+genpts` is redundant but harmless.
    case "$OPTS" in
        *a*)
            set -- "$@" '-avoid_negative_ts' 'disabled'  # 0
        ;;
        *)
            set -- "$@" '-fflags' '+genpts'
        ;;
    esac

    set -- "$@" '-f' 'concat'
    set -- "$@" '-safe' '0'
    set -- "$@" '-i' 'ShePoludeem.txt'  # kaam ti
    set -- "$@" '-c' 'copy'
    set -- "$@" '-map' '0'

    case "$OPTS" in
        *i*) set -- "$@" '-map_metadata' '1' ;;
    esac

    case "$OPTS" in
        *d*) set -- "$@" '-loglevel' 'debug' ;;
    esac

    set -- "$@" '-f' "$FMT"
    set -- "$@" "${IN##*/}"

    "$@"

    rm -f ShePoludeem.txt  # (poludqvam)

    # from now on guarantee $FILE is just the filename as we are in our dir
    # simplifies operations
    set -- *
    FILE="$1"
    if [ ! -e "$FILE" ]; then
        set -- .*; while [ "$1" ]; do case "$1" in
            '.' | '..') shift ;;
            *) FILE="$1" && break ;;
        esac; done
    fi
    [ -e "$FILE" ] || { printf "%s\n" 'File glob failed. (ENOENT)'; exit 1; }
    [ ! -d "$FILE" ] || { printf "%s\n" 'File glob failed. (EISDIR)'; exit 1; }

    case "$OPTS" in
        *m*) : ;;
        *n*) touch -r "$IN2" "$FILE" ;;
        *) touch -r "$IN" "$FILE" ;;
    esac

    # rename in our dir
    # if $IN has extension, append it to $FNAME
    if [ "$FNAME" ]; then
        case "$IN" in
            *.?? | *.??? | *.????) FNAME="$FNAME.${IN##*.}" ;;
        esac

        # guard same filename rename
        case "$FILE" in
            "$FNAME") : ;;
            *) mv "$FILE" "$FNAME" ;;
        esac

        FILE="$FNAME"
    fi

    # move result to dest
    case "$OPTS" in
        *t*)
            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$ODIR"/"$FILE" '\033[0m'
        ;;
        *)
            # guaranteed move, no need for guard
            # `-f` because typically output loc/name might match input loc
            mv -f "$FILE" "$DIR"/"$FILE"

            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$DIR"/"$FILE" '\033[0m'
        ;;
    esac
)

ffmpeg_concat "$@"
