#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

ffmpeg_merge() (
    err() {
        trap - INT TERM EXIT

        if [ "$1" != 0 ]; then
            printf "%s" \
'
$1 -> (video) input
$2 -> (audio) input
$3 -> (subtitles) input
$4 -> fname
$5 *d* -> `-loglevel debug`
$5 *m* -> dont keep mtime
$5 *n* -> keep mtime of input 2
$5 *s* -> pass `-c:s mov_text`
$5 *t* -> no cleanup/move (only on success)
$5 *u* -> work in current dir
'

            rm -rf "$ODIR"
        fi

        case "$OPTS" in
            *t*) : ;;
            *) rm -rf "$ODIR" ;;
        esac

        exit "$1"
    }

    set -e
    trap "err \$?" INT TERM EXIT

    IN="$1"
    IN2="$2"
    IN3="$3"
    FNAME="$4"
    OPTS="$5"
    DIR=$(cd -Pe "$PWD" && printf "%s" "$PWD.")
    DIR="${DIR%.}"

    case "$OPTS" in
        *u*) ODIR="$DIR"/.ffmpeg_merge ;;
        *) ODIR="${TMPDIR:-/tmp}"/.ffmpeg_merge ;;
    esac

    [ "$IN" ] || { printf "%s\n" 'No first input file specified.'; exit 2; }
    [ -e "$IN" ] || { printf "%s\n" 'Bad first input. (ENOENT)'; exit 2; }
    [ ! -d "$IN" ] || { printf "%s\n" 'Bad first input. (EISDIR)'; exit 2; }

    case "$IN" in
        */*)
            IN="$(realpath -- "$IN" && printf "%s" .)"
            IN="${IN%?.}"

            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            DIR="${IN%/*}"
        ;;
        *)
            # assert $IN has extension or prompt for the format
            # input files dont need specification, but output files do
            case "$IN" in
                *.?? | *.??? | *.????)
                    FMT="${IN##*.}"
                ;;
                *)
                    printf "%s%s" \
                        'Honey, please tell me the output file format ' \
                        'in ffmpeg notation: '

                    read -r FMT
                    if [ ! "$FMT" ]; then
                        printf "%s\n" 'No format specified.'; exit 2
                    fi
                ;;
            esac

            IN="$DIR"/"$IN"
        ;;
    esac

    [ -e "$IN" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }

    # require at least either of $IN2 or $IN3
    [ "$IN2" ] || [ "$IN3" ] || {
        printf "%s\n" 'No second input specified.'; exit 2
    }

    if [ "$IN2" ]; then
        [ -e "$IN2" ] || { printf "%s\n" 'Bad second input. (ENOENT)'; exit 2; }
        [ ! -d "$IN2" ] || { printf "%s\n" 'Bad second input. (EISDIR)'; exit 2; }

        IN2="$(realpath -- "$IN2" && printf "%s" .)"
        IN2="${IN2%?.}"

        [ -e "$IN2" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }
    fi

    if [ "$IN3" ]; then
        [ -e "$IN3" ] || { printf "%s\n" 'Bad third input. (ENOENT)'; exit 2; }
        [ ! -d "$IN3" ] || { printf "%s\n" 'Bad third input. (EISDIR)'; exit 2; }

        IN3="$(realpath -- "$IN3" && printf "%s" .)"
        IN3="${IN3%?.}"

        [ -e "$IN3" ] || { printf "%s\n" 'Resolution error. (ENOENT)'; exit 1; }
    fi

    case "${IN##*.}.${IN2##*.}" in
        'm4a.mp4')
            printf "%s" 'I think we should swap $1/$2, honey? [Y/n] '

            read -r _action; [ "$_action" ] || _action=Y
            case "$_action" in
                [Yy]*)
                    set -- "$IN2" "$IN" "${IN2%/*}"

                    IN="$1"
                    IN2="$2"
                    DIR="$3"
                ;;
            esac
        ;;
    esac

    # guarantee we are in our custom empty dir
    # otherwise globbing cannot be trusted
    rm -rf "$ODIR"
    mkdir "$ODIR"
    cd "$ODIR"

    set -- 'ffmpeg'
    set -- "$@" '-hide_banner'

    set -- "$@" '-i' "$IN"
    if [ "$IN2" ]; then
        set -- "$@" '-i' "$IN2"
    fi
    if [ "$IN3" ]; then
        set -- "$@" '-i' "$IN3"
    fi
    set -- "$@" '-c' 'copy'
    set -- "$@" '-copy_unknown'
    set -- "$@" '-map' '0'
    if [ "$IN2" ]; then
        set -- "$@" '-map' '1'
    fi
    if [ "$IN3" ]; then
        set -- "$@" '-map' '2'
    fi
    set -- "$@" '-map_metadata' '0'

    case "$OPTS" in
        *d*) set -- "$@" '-loglevel' 'debug' ;;
    esac

    # works on the first subtitle output stream; not related to input streams.
    # warning is normal due to global (but intended) `-c copy`
    case "$OPTS" in
        *s*) set -- "$@" '-c:s' 'mov_text' ;;
    esac

    set -- "$@" '-f' "$FMT"
    set -- "$@" "${IN##*/}"

    "$@"

    # from now on guarantee $FILE is just the filename as we are in our dir
    # simplifies operations
    set -- *
    FILE="$1"
    if [ ! -e "$FILE" ]; then
        set -- .*; while [ "$1" ]; do case "$1" in
            '.' | '..') shift ;;
            *) FILE="$1" && break ;;
        esac; done
    fi
    [ -e "$FILE" ] || { printf "%s\n" 'File glob failed. (ENOENT)'; exit 1; }
    [ ! -d "$FILE" ] || { printf "%s\n" 'File glob failed. (EISDIR)'; exit 1; }

    case "$OPTS" in
        *m*) : ;;
        *n*) touch -r "$IN2" "$FILE" ;;
        *) touch -r "$IN" "$FILE" ;;
    esac

    # rename in our dir
    # if $IN has extension, append it to $FNAME
    if [ "$FNAME" ]; then
        case "$IN" in
            *.?? | *.??? | *.????) FNAME="$FNAME.${IN##*.}" ;;
        esac

        # guard same filename rename
        case "$FILE" in
            "$FNAME") : ;;
            *) mv "$FILE" "$FNAME" ;;
        esac

        FILE="$FNAME"
    fi

    # move result to dest
    case "$OPTS" in
        *t*)
            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$ODIR"/"$FILE" '\033[0m'
        ;;
        *)
            # guaranteed move, no need for guard
            # `-f` because typically output loc/name might match input loc
            mv -f "$FILE" "$DIR"/"$FILE"

            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$DIR"/"$FILE" '\033[0m'
        ;;
    esac
)

ffmpeg_merge "$@"
