#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

yt_a() (
    err() {
        trap - INT TERM EXIT

        if [ "$1" != 0 ]; then
            printf "%s" \
'
$1 -> url
$2 -> fname
$3 *0* -> `--format bestaudio[format_id~=^140][language^=en]`, yt-dlp only
$3 *3* -> dont use cookies,                                    yt-dlp only
$3 *b* -> `--format bestaudio`
$3 *f* -> dont recognize/append extension, fname is fully authoritative
$3 *m* -> dont use `--mtime`
$3 *n* -> `--fixup never`
$3 *t* -> `--no-part --no-cache-dir`, no cleanup/move (only on success)
$3 *u* -> download in current dir
$3 *v* -> `--verbose`
$3 *y* -> use yt-dlp
$3 *z* -> use youtube-dl
'

            rm -rf "$ODIR"
        fi

        case "$OPTS" in
            *t*) : ;;
            *) rm -rf "$ODIR" ;;
        esac

        exit "$1"
    }

    set -e
    trap "err \$?" INT TERM EXIT

    URL="$1"
    FNAME="$2"
    OPTS="$3"
    DIR="$PWD"
    FILE=

    case "$OPTS" in
        *u*) ODIR="$DIR"/.yt_a ;;
        *) ODIR="${TMPDIR:-/tmp}"/.yt_a ;;
    esac

    [ "$URL" ] || { printf "%s\n" 'No URL specified.'; exit 2; }

    # guarantee we are in our custom empty dir
    # otherwise globbing cannot be trusted
    rm -rf "$ODIR"
    mkdir "$ODIR"
    cd "$ODIR"

    case "$OPTS" in
        *y*)
            set -- 'yt-dlp'
        ;;
        *z*)
            set -- 'youtube-dl'
        ;;
        *)
            if command -v 'yt-dlp' > /dev/null 2>&1; then
                set -- 'yt-dlp'; OPTS="$OPTS"y
            elif command -v 'youtube-dl' > /dev/null 2>&1; then
                set -- 'youtube-dl'; OPTS="$OPTS"z
            else
                printf "%s\n" 'No downloader found.'; exit 1
            fi
        ;;
    esac

    case "$OPTS" in
        *m*) : ;;
        *) [ "$1" = 'yt-dlp' ] && set -- "$@" '--mtime' || : ;;
    esac

    case "$OPTS" in
        *t*) set -- "$@" '--no-part' '--no-cache-dir' ;;
    esac

    case "$OPTS" in
        *n*) set -- "$@" '--fixup' 'never' ;;
    esac

    case "$OPTS" in
        *v*) set -- "$@" '--verbose' ;;
    esac

    case "$OPTS" in
        *3*)
            set -- "$@" '--extractor-args' 'youtube:formats=missing_pot'
        ;;
        *y*)
            set -- "$@" '--cookies-from-browser' 'firefox'
            set -- "$@" '--extractor-args' 'youtube:formats=missing_pot'
        ;;
    esac

    # 141 - 256 kbps aac, contained in mp4(m4a); premium accounts only
    # 140 - 128 kbps aac, contained in mp4(m4a)
    case "$OPTS" in
        *0*)
            set -- "$@" '--format' 'bestaudio[format_id~='\''^140'\''][language^=en]'
        ;;
        *b*)
            set -- "$@" '--format' 'bestaudio'
        ;;
        *)
            set -- "$@" '--format' '141/140'
        ;;
    esac

    set -- "$@" "$URL"

    "$@"

    # from now on guarantee $FILE is just the filename as we are in our dir
    # simplifies operations
    FILE=$(set -- *; printf "%s" "$1.")
    FILE="${FILE%.}"
    FILE="${FILE##*/}"

    # rename in our dir
    # if $FILE has extension, append it to $FNAME
    if [ "$FNAME" ]; then
        case "$OPTS" in
            *f*)
                :
            ;;
            *)
                case "$FILE" in
                    *.?? | *.??? | *.????) FNAME="$FNAME.${FILE##*.}" ;;
                esac
            ;;
        esac

        # guard same filename rename
        case "$FILE" in
            "$FNAME") : ;;
            *) mv "$FILE" "$FNAME" ;;
        esac

        FILE="$FNAME"
    fi

    # move result to dest
    case "$OPTS" in
        *t*)
            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$ODIR"/"$FILE" '\033[0m'
        ;;
        *)
            # guaranteed move, no need for guard
            # `-f` because typically output loc/name might match input loc
            mv -f "$FILE" "$DIR"/"$FILE"

            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$DIR"/"$FILE" '\033[0m'
        ;;
    esac
)

yt_a "$@"
