#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only

yt_v() (
    err() {
        trap - INT TERM EXIT

        if [ "$1" != 0 ]; then
            printf "%s" \
'
$1 -> url
$2 -> fname
$3 -> cookies.txt path
$4 *1* -> `--format bestvideo[height<=1080]`, yt-dlp only
$4 *2* -> `--format bestvideo[height<=1440]`, yt-dlp only
$4 *b* -> `--format bestvideo`
$4 *c* -> check for unknown avc1 formats
$4 *d* -> check for unknown avc1 formats with specified config as well
$4 *f* -> dont recognize/append extension, fname is fully authoritative
$4 *m* -> dont use `--mtime`
$4 *n* -> `--fixup never`
$4 *o* -> dont use `-o` / dont custom format filename
$4 *t* -> `--no-part --no-cache-dir`, no cleanup/move (only on success)
$4 *u* -> download in current dir
$4 *v* -> `--verbose`
$4 *y* -> use yt-dlp
$4 *z* -> use youtube-dl
'

            rm -rf "$ODIR"
        fi

        case "$OPTS" in
            *t*) : ;;
            *) rm -rf "$ODIR" ;;
        esac

        exit "$1"
    }

    set -e
    _destroy_cookies=
    ODIR=
    trap "err \$?" INT TERM EXIT

    URL="$1"
    FNAME="$2"
    COOKIES="$3"
    OPTS="$4"
    DIR="$PWD"
    FILE=

    case "$OPTS" in
        *u*) _ODIR="$DIR"/.yt_v ;;
        *) _ODIR="${TMPDIR:-/tmp}"/.yt_v ;;
    esac

    if [ -e "$_ODIR" ]; then
        printf "%s" "Sweetie, '$_ODIR' already exists... Shall I delete it? [y/N] "

        read -r _action; [ "$_action" ] || _action=N
        case "$_action" in
            [Yy]*) ODIR="$_ODIR" ;;
            *) printf "%s\n" 'Sweetheart... wise choice! Deal with it.'; exit 1 ;;
        esac
    else
        ODIR="$_ODIR"
    fi

    [ "$URL" ] || { printf "%s\n" 'No URL specified.'; exit 2; }
    if [ "$COOKIES" ]; then
        if [ ! -e "$COOKIES" ]; then
            printf "%s\n" 'Bad cookies.txt file. (ENOENT)'; exit 2
        fi
    fi

    # guarantee we are in our custom empty dir
    # otherwise globbing cannot be trusted
    rm -rf "$ODIR"
    mkdir "$ODIR"
    cd "$ODIR"

    # scan for cookies.txt file
    if [ ! "$COOKIES" ]; then while :; do
        set -- *cookies.txt ../*cookies.txt
        while [ "$#" -ge 1 ] || break 2; do
            [ -e "$1" ] && break || shift
        done

        _cookies="$1"
        _cookies="$(realpath -- "$_cookies" && printf "%s" .)"
        _cookies="${_cookies%?.}"

        printf "%s" "Honey, should I use the cookies at '$_cookies'? [y/N] "

        read -r _action; [ "$_action" ] || _action=N
        case "$_action" in
            [Yy]*) COOKIES="$_cookies"; _destroy_cookies=1 ;;
            *) printf "%s\n" 'Will not use the cookies.' ;;
        esac

        break
    done; fi

    case "$OPTS" in
        *y*)
            set -- 'yt-dlp'
        ;;
        *z*)
            set -- 'youtube-dl'
        ;;
        *)
            if command -v 'yt-dlp' > /dev/null 2>&1; then
                set -- 'yt-dlp'; OPTS="$OPTS"y
            elif command -v 'youtube-dl' > /dev/null 2>&1; then
                set -- 'youtube-dl'; OPTS="$OPTS"z
            else
                printf "%s\n" 'No downloader found.'; exit 1
            fi
        ;;
    esac

    case "$OPTS" in
        *c* | *d*)
            OUT=$(
            case "$OPTS" in *y*) set -- "$@" '--extractor-args' 'youtube:formats=missing_pot' ;; esac

            "$@" \
                -F "$URL" | grep avc | awk \
                '$1 !~ /^(299|312|137|270|298|311|379|214|136|232|22|135|231|134|230|18|133|229|160|269)$/' 2>/dev/null
            ) || :

            if [ "$OUT" ]; then
                printf "%s\n%s\n" 'Found formats:' "$OUT"
            else
                printf "%s\n" 'No new formats.'
            fi

            case "$OPTS" in
                *c*) exit 0 ;;
            esac
        ;;
    esac

    case "$OPTS" in
        *m*) : ;;
        *) [ "$1" = 'yt-dlp' ] && set -- "$@" '--mtime' || : ;;
    esac

    case "$OPTS" in
        *o*) : ;;
        *) [ "$1" = 'yt-dlp' ] && set -- "$@" '-o' '%(title)s [%(id)s %(upload_date)s].%(ext)s' || : ;;
    esac

    case "$OPTS" in
        *t*) set -- "$@" '--no-part' '--no-cache-dir' ;;
    esac

    case "$OPTS" in
        *n*) set -- "$@" '--fixup' 'never' ;;
    esac

    case "$OPTS" in
        *v*) set -- "$@" '--verbose' ;;
    esac

    case "$OPTS" in
        *y*) set -- "$@" '--extractor-args' 'youtube:formats=missing_pot' ;;
    esac

    if [ "$COOKIES" ]; then
        set -- "$@" '--cookies' "$COOKIES"
    fi

    case "$OPTS" in
        *d*)
            OUT=$(
            "$@" \
                -F "$URL" | grep avc | awk \
                '$1 !~ /^(299|312|137|270|298|311|379|214|136|232|22|135|231|134|230|18|133|229|160|269)$/' 2>/dev/null
            ) || :

            if [ "$OUT" ]; then
                printf "%s\n%s\n" 'Found formats:' "$OUT"
            else
                printf "%s\n" 'Also no new formats.'
            fi

            exit 0
        ;;
    esac

    # 299/312 - 1080p HFR avc1(h.264), contained in mp4
    # 137/270 - 1080p avc1(h.264), contained in mp4
    # 298/311 - 720p HFR avc1(h.264), contained in mp4
    # 379/214 - 720p HBR avc1(h.264), contained in mp4
    # 136/232 - 720p avc1(h.264), contained in mp4
    # 135/231 - 480p avc1(h.264), contained in mp4
    # 134/230 - 360p avc1(h.264), contained in mp4
    # 133/229 - 240p avc1(h.264), contained in mp4
    # 160/269 - 144p avc1(h.264), contained in mp4
    case "$OPTS" in
        *1*)
            set -- "$@" '--format' 'bestvideo[height<=1080]'
        ;;
        *2*)
            set -- "$@" '--format' 'bestvideo[height<=1440]'
        ;;
        *b*)
            set -- "$@" '--format' 'bestvideo'
        ;;
        *)
            set -- "$@" '--format' '299/137/298/379/136/135/134/133/160'
        ;;
    esac

    set -- "$@" "$URL"

    "$@"

    # from now on guarantee $FILE is just the filename as we are in our dir
    # simplifies operations
    set -- *
    FILE="$1"
    if [ ! -e "$FILE" ]; then
        set -- .*; while [ "$1" ]; do case "$1" in
            '.' | '..') shift ;;
            *) FILE="$1" && break ;;
        esac; done
    fi
    [ -e "$FILE" ] || { printf "%s\n" 'File glob failed. (ENOENT)'; exit 1; }
    [ ! -d "$FILE" ] || { printf "%s\n" 'File glob failed. (EISDIR)'; exit 1; }

    # rename in our dir
    # if $FILE has extension, append it to $FNAME
    if [ "$FNAME" ]; then
        case "$OPTS" in
            *f*)
                :
            ;;
            *)
                case "$FILE" in
                    *.?? | *.??? | *.????) FNAME="$FNAME.${FILE##*.}" ;;
                esac
            ;;
        esac

        # guard same filename rename
        case "$FILE" in
            "$FNAME") : ;;
            *) mv "$FILE" "$FNAME" ;;
        esac

        FILE="$FNAME"
    fi

    # move result to dest
    case "$OPTS" in
        *t*)
            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$ODIR"/"$FILE" '\033[0m'
        ;;
        *)
            # guaranteed move, no need for guard
            # `-f` because typically output loc/name might match input loc
            mv -f "$FILE" "$DIR"/"$FILE"

            printf "%b%s%b %b%s%b\n" \
                '\033[1;32m' 'FILE:' '\033[0m' \
                '\033[1;37m' "$DIR"/"$FILE" '\033[0m'
        ;;
    esac

    # remaining unrelated stuff to do
    if [ "$_destroy_cookies" ]; then
        rm -f "$COOKIES"
        printf "%s\n" "Deleted the cookies '$COOKIES'."
    fi
)

yt_v "$@"
